# path to a directory with all packages
storage: ./.verdaccio

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  "**":
    access: $anonymous
    publish: $anonymous
    proxy: npmjs

auth:
  htpasswd:
    file: ./htpasswd
    max_users: -1

server:
  keepAliveTimeout: 60

logs:
  - { type: stdout, format: pretty, level: http }
