name: Build (latest)

on:
  push:
    branches: [ci/cypress]

env:
  NODE_OPTIONS: --max_old_space_size=4096
  MONGODB_SERVER: ${{ secrets.MONGODB_SERVER }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build-test-release:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Setup .env.json files
        run: yarn setup-env-files:ci

      - name: Build packages
        run: yarn build

      - name: Deploy API stack
        run: yarn webiny deploy api --env prod

      - name: Deploy Apps stack
        run: yarn webiny deploy apps --env prod

      - name: Setup Cypress config
        run: yarn setup-cypress

      - name: Run Admin Installation Test
        run: yarn cypress run --spec "cypress/integration/adminInstallation/**/*.spec.js"

      - name: Run Admin Installation Test
        run: yarn cypress run --spec "cypress/integration/admin/**/*.spec.js"
