name: Pull Request (v5)

on:
  push:
    branches: [next]

env:
  NODE_OPTIONS: --max_old_space_size=4096

jobs:
  initial-checks:
    name: Initial checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"

      - name: Install dependencies
        run: yarn --immutable

      - name: Check code formatting
        run: yarn prettier:check

      - name: Check dependencies
        run: yarn adio

      - name: Check TS configs
        run: yarn check-ts-configs

      - name: ESLint
        run: yarn eslint

  validate-commits:
    name: Validate commit messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webiny/action-conventional-commits@v1.0.2

  build-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"

      - name: Install dependencies
        run: yarn --immutable

      - name: Build packages
        run: yarn build

      - name: Run tests
        run: yarn test

  cwp-test:
    name: Test "create-webiny-project"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"

      - name: Install dependencies
        run: yarn --immutable

      - name: Build packages
        run: yarn build

      - name: Configure NPM to use local registry
        run: npm config set registry http://localhost:4873

      - name: Start Verdaccio local server
        run: pm2 start verdaccio

      - name: Set git email
        run: git config --global user.email "info@webiny.com"

      - name: Set git username
        run: git config --global user.name "webiny"

      - name: Version packages (no push, no changelog)
        run: yarn lerna version --conventional-prerelease --force-publish --preid beta --no-push --no-changelog

      - name: Release to Verdaccio
        run: yarn lerna publish from-package --force-publish --dist-tag beta --registry="http://localhost:4873" --no-verify-access --no-verify-registry

      - name: Create a new Webiny project
        run: npx create-webiny-project@beta test-project --tag beta --no-interactive --template-options '{"region":"eu-central-1","vpc":false}'

      - name: Execute some tests
        run: echo 'TODO'
